// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fk-data.proto

package fk_data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DownloadFlags int32

const (
	DownloadFlags_READING_FLAGS_NONE          DownloadFlags = 0
	DownloadFlags_READING_FLAGS_NOT_RECORDING DownloadFlags = 1
	DownloadFlags_READING_FLAGS_MANUAL        DownloadFlags = 2
)

var DownloadFlags_name = map[int32]string{
	0: "READING_FLAGS_NONE",
	1: "READING_FLAGS_NOT_RECORDING",
	2: "READING_FLAGS_MANUAL",
}

var DownloadFlags_value = map[string]int32{
	"READING_FLAGS_NONE":          0,
	"READING_FLAGS_NOT_RECORDING": 1,
	"READING_FLAGS_MANUAL":        2,
}

func (x DownloadFlags) String() string {
	return proto.EnumName(DownloadFlags_name, int32(x))
}

func (DownloadFlags) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{0}
}

type ConditionFlags int32

const (
	ConditionFlags_CONDITION_FLAGS_NONE      ConditionFlags = 0
	ConditionFlags_CONDITION_FLAGS_RECORDING ConditionFlags = 1
)

var ConditionFlags_name = map[int32]string{
	0: "CONDITION_FLAGS_NONE",
	1: "CONDITION_FLAGS_RECORDING",
}

var ConditionFlags_value = map[string]int32{
	"CONDITION_FLAGS_NONE":      0,
	"CONDITION_FLAGS_RECORDING": 1,
}

func (x ConditionFlags) String() string {
	return proto.EnumName(ConditionFlags_name, int32(x))
}

func (ConditionFlags) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{1}
}

type SignedRecordKind int32

const (
	SignedRecordKind_SIGNED_RECORD_KIND_NONE      SignedRecordKind = 0
	SignedRecordKind_SIGNED_RECORD_KIND_MODULES   SignedRecordKind = 1
	SignedRecordKind_SIGNED_RECORD_KIND_SCHEDULE  SignedRecordKind = 2
	SignedRecordKind_SIGNED_RECORD_KIND_STATE     SignedRecordKind = 3
	SignedRecordKind_SIGNED_RECORD_KIND_RAW_STATE SignedRecordKind = 4
	SignedRecordKind_SIGNED_RECORD_KIND_OTHER     SignedRecordKind = 255
)

var SignedRecordKind_name = map[int32]string{
	0:   "SIGNED_RECORD_KIND_NONE",
	1:   "SIGNED_RECORD_KIND_MODULES",
	2:   "SIGNED_RECORD_KIND_SCHEDULE",
	3:   "SIGNED_RECORD_KIND_STATE",
	4:   "SIGNED_RECORD_KIND_RAW_STATE",
	255: "SIGNED_RECORD_KIND_OTHER",
}

var SignedRecordKind_value = map[string]int32{
	"SIGNED_RECORD_KIND_NONE":      0,
	"SIGNED_RECORD_KIND_MODULES":   1,
	"SIGNED_RECORD_KIND_SCHEDULE":  2,
	"SIGNED_RECORD_KIND_STATE":     3,
	"SIGNED_RECORD_KIND_RAW_STATE": 4,
	"SIGNED_RECORD_KIND_OTHER":     255,
}

func (x SignedRecordKind) String() string {
	return proto.EnumName(SignedRecordKind_name, int32(x))
}

func (SignedRecordKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{2}
}

type DeviceLocation struct {
	Enabled              uint32    `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Fix                  uint32    `protobuf:"varint,1,opt,name=fix,proto3" json:"fix,omitempty"`
	Time                 int64     `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Longitude            float32   `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float32   `protobuf:"fixed32,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Altitude             float32   `protobuf:"fixed32,5,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Coordinates          []float32 `protobuf:"fixed32,6,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	Satellites           uint32    `protobuf:"varint,8,opt,name=satellites,proto3" json:"satellites,omitempty"`
	Hdop                 uint32    `protobuf:"varint,9,opt,name=hdop,proto3" json:"hdop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeviceLocation) Reset()         { *m = DeviceLocation{} }
func (m *DeviceLocation) String() string { return proto.CompactTextString(m) }
func (*DeviceLocation) ProtoMessage()    {}
func (*DeviceLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{0}
}

func (m *DeviceLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceLocation.Unmarshal(m, b)
}
func (m *DeviceLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceLocation.Marshal(b, m, deterministic)
}
func (m *DeviceLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceLocation.Merge(m, src)
}
func (m *DeviceLocation) XXX_Size() int {
	return xxx_messageInfo_DeviceLocation.Size(m)
}
func (m *DeviceLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceLocation.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceLocation proto.InternalMessageInfo

func (m *DeviceLocation) GetEnabled() uint32 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

func (m *DeviceLocation) GetFix() uint32 {
	if m != nil {
		return m.Fix
	}
	return 0
}

func (m *DeviceLocation) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *DeviceLocation) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *DeviceLocation) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *DeviceLocation) GetAltitude() float32 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *DeviceLocation) GetCoordinates() []float32 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *DeviceLocation) GetSatellites() uint32 {
	if m != nil {
		return m.Satellites
	}
	return 0
}

func (m *DeviceLocation) GetHdop() uint32 {
	if m != nil {
		return m.Hdop
	}
	return 0
}

type SensorReading struct {
	Reading              uint32   `protobuf:"varint,1,opt,name=reading,proto3" json:"reading,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Sensor               uint32   `protobuf:"varint,3,opt,name=sensor,proto3" json:"sensor,omitempty"`
	Value                float32  `protobuf:"fixed32,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SensorReading) Reset()         { *m = SensorReading{} }
func (m *SensorReading) String() string { return proto.CompactTextString(m) }
func (*SensorReading) ProtoMessage()    {}
func (*SensorReading) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{1}
}

func (m *SensorReading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensorReading.Unmarshal(m, b)
}
func (m *SensorReading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensorReading.Marshal(b, m, deterministic)
}
func (m *SensorReading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensorReading.Merge(m, src)
}
func (m *SensorReading) XXX_Size() int {
	return xxx_messageInfo_SensorReading.Size(m)
}
func (m *SensorReading) XXX_DiscardUnknown() {
	xxx_messageInfo_SensorReading.DiscardUnknown(m)
}

var xxx_messageInfo_SensorReading proto.InternalMessageInfo

func (m *SensorReading) GetReading() uint32 {
	if m != nil {
		return m.Reading
	}
	return 0
}

func (m *SensorReading) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SensorReading) GetSensor() uint32 {
	if m != nil {
		return m.Sensor
	}
	return 0
}

func (m *SensorReading) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type LoggedReading struct {
	Version              uint32          `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Location             *DeviceLocation `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Reading              *SensorReading  `protobuf:"bytes,3,opt,name=reading,proto3" json:"reading,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoggedReading) Reset()         { *m = LoggedReading{} }
func (m *LoggedReading) String() string { return proto.CompactTextString(m) }
func (*LoggedReading) ProtoMessage()    {}
func (*LoggedReading) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{2}
}

func (m *LoggedReading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoggedReading.Unmarshal(m, b)
}
func (m *LoggedReading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoggedReading.Marshal(b, m, deterministic)
}
func (m *LoggedReading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoggedReading.Merge(m, src)
}
func (m *LoggedReading) XXX_Size() int {
	return xxx_messageInfo_LoggedReading.Size(m)
}
func (m *LoggedReading) XXX_DiscardUnknown() {
	xxx_messageInfo_LoggedReading.DiscardUnknown(m)
}

var xxx_messageInfo_LoggedReading proto.InternalMessageInfo

func (m *LoggedReading) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *LoggedReading) GetLocation() *DeviceLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *LoggedReading) GetReading() *SensorReading {
	if m != nil {
		return m.Reading
	}
	return nil
}

type SensorAndValue struct {
	Sensor               uint32   `protobuf:"varint,1,opt,name=sensor,proto3" json:"sensor,omitempty"`
	Value                float32  `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SensorAndValue) Reset()         { *m = SensorAndValue{} }
func (m *SensorAndValue) String() string { return proto.CompactTextString(m) }
func (*SensorAndValue) ProtoMessage()    {}
func (*SensorAndValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{3}
}

func (m *SensorAndValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensorAndValue.Unmarshal(m, b)
}
func (m *SensorAndValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensorAndValue.Marshal(b, m, deterministic)
}
func (m *SensorAndValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensorAndValue.Merge(m, src)
}
func (m *SensorAndValue) XXX_Size() int {
	return xxx_messageInfo_SensorAndValue.Size(m)
}
func (m *SensorAndValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SensorAndValue.DiscardUnknown(m)
}

var xxx_messageInfo_SensorAndValue proto.InternalMessageInfo

func (m *SensorAndValue) GetSensor() uint32 {
	if m != nil {
		return m.Sensor
	}
	return 0
}

func (m *SensorAndValue) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ModuleHeader struct {
	Manufacturer         uint32   `protobuf:"varint,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Kind                 uint32   `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Version              uint32   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleHeader) Reset()         { *m = ModuleHeader{} }
func (m *ModuleHeader) String() string { return proto.CompactTextString(m) }
func (*ModuleHeader) ProtoMessage()    {}
func (*ModuleHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{4}
}

func (m *ModuleHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleHeader.Unmarshal(m, b)
}
func (m *ModuleHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleHeader.Marshal(b, m, deterministic)
}
func (m *ModuleHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleHeader.Merge(m, src)
}
func (m *ModuleHeader) XXX_Size() int {
	return xxx_messageInfo_ModuleHeader.Size(m)
}
func (m *ModuleHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleHeader proto.InternalMessageInfo

func (m *ModuleHeader) GetManufacturer() uint32 {
	if m != nil {
		return m.Manufacturer
	}
	return 0
}

func (m *ModuleHeader) GetKind() uint32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *ModuleHeader) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type ModuleInfo struct {
	Position             uint32        `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Address              uint32        `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Header               *ModuleHeader `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	Firmware             *Firmware     `protobuf:"bytes,5,opt,name=firmware,proto3" json:"firmware,omitempty"`
	Sensors              []*SensorInfo `protobuf:"bytes,6,rep,name=sensors,proto3" json:"sensors,omitempty"`
	Id                   []byte        `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	Flags                uint32        `protobuf:"varint,8,opt,name=flags,proto3" json:"flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ModuleInfo) Reset()         { *m = ModuleInfo{} }
func (m *ModuleInfo) String() string { return proto.CompactTextString(m) }
func (*ModuleInfo) ProtoMessage()    {}
func (*ModuleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{5}
}

func (m *ModuleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleInfo.Unmarshal(m, b)
}
func (m *ModuleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleInfo.Marshal(b, m, deterministic)
}
func (m *ModuleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleInfo.Merge(m, src)
}
func (m *ModuleInfo) XXX_Size() int {
	return xxx_messageInfo_ModuleInfo.Size(m)
}
func (m *ModuleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleInfo proto.InternalMessageInfo

func (m *ModuleInfo) GetPosition() uint32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *ModuleInfo) GetAddress() uint32 {
	if m != nil {
		return m.Address
	}
	return 0
}

func (m *ModuleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModuleInfo) GetHeader() *ModuleHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ModuleInfo) GetFirmware() *Firmware {
	if m != nil {
		return m.Firmware
	}
	return nil
}

func (m *ModuleInfo) GetSensors() []*SensorInfo {
	if m != nil {
		return m.Sensors
	}
	return nil
}

func (m *ModuleInfo) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ModuleInfo) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

type SensorInfo struct {
	Number               uint32   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UnitOfMeasure        string   `protobuf:"bytes,3,opt,name=unitOfMeasure,proto3" json:"unitOfMeasure,omitempty"`
	Flags                uint32   `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SensorInfo) Reset()         { *m = SensorInfo{} }
func (m *SensorInfo) String() string { return proto.CompactTextString(m) }
func (*SensorInfo) ProtoMessage()    {}
func (*SensorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{6}
}

func (m *SensorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensorInfo.Unmarshal(m, b)
}
func (m *SensorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensorInfo.Marshal(b, m, deterministic)
}
func (m *SensorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensorInfo.Merge(m, src)
}
func (m *SensorInfo) XXX_Size() int {
	return xxx_messageInfo_SensorInfo.Size(m)
}
func (m *SensorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SensorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SensorInfo proto.InternalMessageInfo

func (m *SensorInfo) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *SensorInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SensorInfo) GetUnitOfMeasure() string {
	if m != nil {
		return m.UnitOfMeasure
	}
	return ""
}

func (m *SensorInfo) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

type Firmware struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Build                string   `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	Number               string   `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	Timestamp            uint64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hash                 string   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Firmware) Reset()         { *m = Firmware{} }
func (m *Firmware) String() string { return proto.CompactTextString(m) }
func (*Firmware) ProtoMessage()    {}
func (*Firmware) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{7}
}

func (m *Firmware) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Firmware.Unmarshal(m, b)
}
func (m *Firmware) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Firmware.Marshal(b, m, deterministic)
}
func (m *Firmware) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Firmware.Merge(m, src)
}
func (m *Firmware) XXX_Size() int {
	return xxx_messageInfo_Firmware.Size(m)
}
func (m *Firmware) XXX_DiscardUnknown() {
	xxx_messageInfo_Firmware.DiscardUnknown(m)
}

var xxx_messageInfo_Firmware proto.InternalMessageInfo

func (m *Firmware) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Firmware) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func (m *Firmware) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Firmware) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Firmware) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Metadata struct {
	DeviceId             []byte        `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Time                 int64         `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Git                  string        `protobuf:"bytes,3,opt,name=git,proto3" json:"git,omitempty"`
	Build                string        `protobuf:"bytes,7,opt,name=build,proto3" json:"build,omitempty"`
	ResetCause           uint32        `protobuf:"varint,4,opt,name=resetCause,proto3" json:"resetCause,omitempty"`
	Sensors              []*SensorInfo `protobuf:"bytes,5,rep,name=sensors,proto3" json:"sensors,omitempty"`
	Modules              []*ModuleInfo `protobuf:"bytes,6,rep,name=modules,proto3" json:"modules,omitempty"`
	Firmware             *Firmware     `protobuf:"bytes,8,opt,name=firmware,proto3" json:"firmware,omitempty"`
	Generation           []byte        `protobuf:"bytes,9,opt,name=generation,proto3" json:"generation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{8}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetDeviceId() []byte {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func (m *Metadata) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Metadata) GetGit() string {
	if m != nil {
		return m.Git
	}
	return ""
}

func (m *Metadata) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func (m *Metadata) GetResetCause() uint32 {
	if m != nil {
		return m.ResetCause
	}
	return 0
}

func (m *Metadata) GetSensors() []*SensorInfo {
	if m != nil {
		return m.Sensors
	}
	return nil
}

func (m *Metadata) GetModules() []*ModuleInfo {
	if m != nil {
		return m.Modules
	}
	return nil
}

func (m *Metadata) GetFirmware() *Firmware {
	if m != nil {
		return m.Firmware
	}
	return nil
}

func (m *Metadata) GetGeneration() []byte {
	if m != nil {
		return m.Generation
	}
	return nil
}

type Status struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Uptime               uint32   `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Battery              float32  `protobuf:"fixed32,3,opt,name=battery,proto3" json:"battery,omitempty"`
	Memory               uint32   `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Busy                 uint64   `protobuf:"varint,5,opt,name=busy,proto3" json:"busy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{9}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Status) GetUptime() uint32 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *Status) GetBattery() float32 {
	if m != nil {
		return m.Battery
	}
	return 0
}

func (m *Status) GetMemory() uint32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Status) GetBusy() uint64 {
	if m != nil {
		return m.Busy
	}
	return 0
}

type LogMessage struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Uptime               uint32   `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Level                uint32   `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Facility             string   `protobuf:"bytes,4,opt,name=facility,proto3" json:"facility,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogMessage) Reset()         { *m = LogMessage{} }
func (m *LogMessage) String() string { return proto.CompactTextString(m) }
func (*LogMessage) ProtoMessage()    {}
func (*LogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{10}
}

func (m *LogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogMessage.Unmarshal(m, b)
}
func (m *LogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogMessage.Marshal(b, m, deterministic)
}
func (m *LogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMessage.Merge(m, src)
}
func (m *LogMessage) XXX_Size() int {
	return xxx_messageInfo_LogMessage.Size(m)
}
func (m *LogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LogMessage proto.InternalMessageInfo

func (m *LogMessage) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LogMessage) GetUptime() uint32 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *LogMessage) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LogMessage) GetFacility() string {
	if m != nil {
		return m.Facility
	}
	return ""
}

func (m *LogMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SensorGroup struct {
	Module               uint32            `protobuf:"varint,1,opt,name=module,proto3" json:"module,omitempty"`
	Readings             []*SensorAndValue `protobuf:"bytes,2,rep,name=readings,proto3" json:"readings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SensorGroup) Reset()         { *m = SensorGroup{} }
func (m *SensorGroup) String() string { return proto.CompactTextString(m) }
func (*SensorGroup) ProtoMessage()    {}
func (*SensorGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{11}
}

func (m *SensorGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensorGroup.Unmarshal(m, b)
}
func (m *SensorGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensorGroup.Marshal(b, m, deterministic)
}
func (m *SensorGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensorGroup.Merge(m, src)
}
func (m *SensorGroup) XXX_Size() int {
	return xxx_messageInfo_SensorGroup.Size(m)
}
func (m *SensorGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_SensorGroup.DiscardUnknown(m)
}

var xxx_messageInfo_SensorGroup proto.InternalMessageInfo

func (m *SensorGroup) GetModule() uint32 {
	if m != nil {
		return m.Module
	}
	return 0
}

func (m *SensorGroup) GetReadings() []*SensorAndValue {
	if m != nil {
		return m.Readings
	}
	return nil
}

type Readings struct {
	Time                 int64           `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Reading              uint32          `protobuf:"varint,2,opt,name=reading,proto3" json:"reading,omitempty"`
	Flags                uint32          `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	Meta                 uint32          `protobuf:"varint,6,opt,name=meta,proto3" json:"meta,omitempty"`
	Uptime               uint32          `protobuf:"varint,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Location             *DeviceLocation `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	SensorGroups         []*SensorGroup  `protobuf:"bytes,5,rep,name=sensorGroups,proto3" json:"sensorGroups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Readings) Reset()         { *m = Readings{} }
func (m *Readings) String() string { return proto.CompactTextString(m) }
func (*Readings) ProtoMessage()    {}
func (*Readings) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{12}
}

func (m *Readings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Readings.Unmarshal(m, b)
}
func (m *Readings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Readings.Marshal(b, m, deterministic)
}
func (m *Readings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Readings.Merge(m, src)
}
func (m *Readings) XXX_Size() int {
	return xxx_messageInfo_Readings.Size(m)
}
func (m *Readings) XXX_DiscardUnknown() {
	xxx_messageInfo_Readings.DiscardUnknown(m)
}

var xxx_messageInfo_Readings proto.InternalMessageInfo

func (m *Readings) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Readings) GetReading() uint32 {
	if m != nil {
		return m.Reading
	}
	return 0
}

func (m *Readings) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *Readings) GetMeta() uint32 {
	if m != nil {
		return m.Meta
	}
	return 0
}

func (m *Readings) GetUptime() uint32 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *Readings) GetLocation() *DeviceLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Readings) GetSensorGroups() []*SensorGroup {
	if m != nil {
		return m.SensorGroups
	}
	return nil
}

type JobSchedule struct {
	Cron                 []byte   `protobuf:"bytes,1,opt,name=cron,proto3" json:"cron,omitempty"`
	Interval             uint32   `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Repeated             uint32   `protobuf:"varint,3,opt,name=repeated,proto3" json:"repeated,omitempty"`
	Duration             uint32   `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Jitter               uint32   `protobuf:"varint,5,opt,name=jitter,proto3" json:"jitter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobSchedule) Reset()         { *m = JobSchedule{} }
func (m *JobSchedule) String() string { return proto.CompactTextString(m) }
func (*JobSchedule) ProtoMessage()    {}
func (*JobSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{13}
}

func (m *JobSchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobSchedule.Unmarshal(m, b)
}
func (m *JobSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobSchedule.Marshal(b, m, deterministic)
}
func (m *JobSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobSchedule.Merge(m, src)
}
func (m *JobSchedule) XXX_Size() int {
	return xxx_messageInfo_JobSchedule.Size(m)
}
func (m *JobSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_JobSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_JobSchedule proto.InternalMessageInfo

func (m *JobSchedule) GetCron() []byte {
	if m != nil {
		return m.Cron
	}
	return nil
}

func (m *JobSchedule) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *JobSchedule) GetRepeated() uint32 {
	if m != nil {
		return m.Repeated
	}
	return 0
}

func (m *JobSchedule) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *JobSchedule) GetJitter() uint32 {
	if m != nil {
		return m.Jitter
	}
	return 0
}

type Schedule struct {
	Readings             *JobSchedule `protobuf:"bytes,1,opt,name=readings,proto3" json:"readings,omitempty"`
	Network              *JobSchedule `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Lora                 *JobSchedule `protobuf:"bytes,3,opt,name=lora,proto3" json:"lora,omitempty"`
	Gps                  *JobSchedule `protobuf:"bytes,4,opt,name=gps,proto3" json:"gps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{14}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetReadings() *JobSchedule {
	if m != nil {
		return m.Readings
	}
	return nil
}

func (m *Schedule) GetNetwork() *JobSchedule {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *Schedule) GetLora() *JobSchedule {
	if m != nil {
		return m.Lora
	}
	return nil
}

func (m *Schedule) GetGps() *JobSchedule {
	if m != nil {
		return m.Gps
	}
	return nil
}

type Identity struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{15}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Condition struct {
	Flags                uint32   `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	Recording            uint32   `protobuf:"varint,2,opt,name=recording,proto3" json:"recording,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{16}
}

func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (m *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(m, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *Condition) GetRecording() uint32 {
	if m != nil {
		return m.Recording
	}
	return 0
}

type NetworkInfo struct {
	Ssid                 string   `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Create               bool     `protobuf:"varint,3,opt,name=create,proto3" json:"create,omitempty"`
	Preferred            bool     `protobuf:"varint,4,opt,name=preferred,proto3" json:"preferred,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkInfo) Reset()         { *m = NetworkInfo{} }
func (m *NetworkInfo) String() string { return proto.CompactTextString(m) }
func (*NetworkInfo) ProtoMessage()    {}
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{17}
}

func (m *NetworkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInfo.Unmarshal(m, b)
}
func (m *NetworkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInfo.Marshal(b, m, deterministic)
}
func (m *NetworkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInfo.Merge(m, src)
}
func (m *NetworkInfo) XXX_Size() int {
	return xxx_messageInfo_NetworkInfo.Size(m)
}
func (m *NetworkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInfo proto.InternalMessageInfo

func (m *NetworkInfo) GetSsid() string {
	if m != nil {
		return m.Ssid
	}
	return ""
}

func (m *NetworkInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NetworkInfo) GetCreate() bool {
	if m != nil {
		return m.Create
	}
	return false
}

func (m *NetworkInfo) GetPreferred() bool {
	if m != nil {
		return m.Preferred
	}
	return false
}

type WifiTransmission struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WifiTransmission) Reset()         { *m = WifiTransmission{} }
func (m *WifiTransmission) String() string { return proto.CompactTextString(m) }
func (*WifiTransmission) ProtoMessage()    {}
func (*WifiTransmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{18}
}

func (m *WifiTransmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WifiTransmission.Unmarshal(m, b)
}
func (m *WifiTransmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WifiTransmission.Marshal(b, m, deterministic)
}
func (m *WifiTransmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WifiTransmission.Merge(m, src)
}
func (m *WifiTransmission) XXX_Size() int {
	return xxx_messageInfo_WifiTransmission.Size(m)
}
func (m *WifiTransmission) XXX_DiscardUnknown() {
	xxx_messageInfo_WifiTransmission.DiscardUnknown(m)
}

var xxx_messageInfo_WifiTransmission proto.InternalMessageInfo

func (m *WifiTransmission) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *WifiTransmission) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *WifiTransmission) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type TransmissionSettings struct {
	Wifi                 *WifiTransmission `protobuf:"bytes,1,opt,name=wifi,proto3" json:"wifi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TransmissionSettings) Reset()         { *m = TransmissionSettings{} }
func (m *TransmissionSettings) String() string { return proto.CompactTextString(m) }
func (*TransmissionSettings) ProtoMessage()    {}
func (*TransmissionSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{19}
}

func (m *TransmissionSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransmissionSettings.Unmarshal(m, b)
}
func (m *TransmissionSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransmissionSettings.Marshal(b, m, deterministic)
}
func (m *TransmissionSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransmissionSettings.Merge(m, src)
}
func (m *TransmissionSettings) XXX_Size() int {
	return xxx_messageInfo_TransmissionSettings.Size(m)
}
func (m *TransmissionSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_TransmissionSettings.DiscardUnknown(m)
}

var xxx_messageInfo_TransmissionSettings proto.InternalMessageInfo

func (m *TransmissionSettings) GetWifi() *WifiTransmission {
	if m != nil {
		return m.Wifi
	}
	return nil
}

type NetworkSettings struct {
	Networks             []*NetworkInfo `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NetworkSettings) Reset()         { *m = NetworkSettings{} }
func (m *NetworkSettings) String() string { return proto.CompactTextString(m) }
func (*NetworkSettings) ProtoMessage()    {}
func (*NetworkSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{20}
}

func (m *NetworkSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkSettings.Unmarshal(m, b)
}
func (m *NetworkSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkSettings.Marshal(b, m, deterministic)
}
func (m *NetworkSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkSettings.Merge(m, src)
}
func (m *NetworkSettings) XXX_Size() int {
	return xxx_messageInfo_NetworkSettings.Size(m)
}
func (m *NetworkSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkSettings.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkSettings proto.InternalMessageInfo

func (m *NetworkSettings) GetNetworks() []*NetworkInfo {
	if m != nil {
		return m.Networks
	}
	return nil
}

type LoraSettings struct {
	DeviceEui            []byte   `protobuf:"bytes,1,opt,name=deviceEui,proto3" json:"deviceEui,omitempty"`
	AppKey               []byte   `protobuf:"bytes,2,opt,name=appKey,proto3" json:"appKey,omitempty"`
	AppEui               []byte   `protobuf:"bytes,3,opt,name=appEui,proto3" json:"appEui,omitempty"`
	FrequencyBand        uint32   `protobuf:"varint,4,opt,name=frequencyBand,proto3" json:"frequencyBand,omitempty"`
	DeviceAddress        []byte   `protobuf:"bytes,5,opt,name=deviceAddress,proto3" json:"deviceAddress,omitempty"`
	NetworkSessionKey    []byte   `protobuf:"bytes,6,opt,name=networkSessionKey,proto3" json:"networkSessionKey,omitempty"`
	AppSessionKey        []byte   `protobuf:"bytes,7,opt,name=appSessionKey,proto3" json:"appSessionKey,omitempty"`
	UplinkCounter        uint32   `protobuf:"varint,8,opt,name=uplinkCounter,proto3" json:"uplinkCounter,omitempty"`
	DownlinkCounter      uint32   `protobuf:"varint,9,opt,name=downlinkCounter,proto3" json:"downlinkCounter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoraSettings) Reset()         { *m = LoraSettings{} }
func (m *LoraSettings) String() string { return proto.CompactTextString(m) }
func (*LoraSettings) ProtoMessage()    {}
func (*LoraSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{21}
}

func (m *LoraSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoraSettings.Unmarshal(m, b)
}
func (m *LoraSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoraSettings.Marshal(b, m, deterministic)
}
func (m *LoraSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoraSettings.Merge(m, src)
}
func (m *LoraSettings) XXX_Size() int {
	return xxx_messageInfo_LoraSettings.Size(m)
}
func (m *LoraSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_LoraSettings.DiscardUnknown(m)
}

var xxx_messageInfo_LoraSettings proto.InternalMessageInfo

func (m *LoraSettings) GetDeviceEui() []byte {
	if m != nil {
		return m.DeviceEui
	}
	return nil
}

func (m *LoraSettings) GetAppKey() []byte {
	if m != nil {
		return m.AppKey
	}
	return nil
}

func (m *LoraSettings) GetAppEui() []byte {
	if m != nil {
		return m.AppEui
	}
	return nil
}

func (m *LoraSettings) GetFrequencyBand() uint32 {
	if m != nil {
		return m.FrequencyBand
	}
	return 0
}

func (m *LoraSettings) GetDeviceAddress() []byte {
	if m != nil {
		return m.DeviceAddress
	}
	return nil
}

func (m *LoraSettings) GetNetworkSessionKey() []byte {
	if m != nil {
		return m.NetworkSessionKey
	}
	return nil
}

func (m *LoraSettings) GetAppSessionKey() []byte {
	if m != nil {
		return m.AppSessionKey
	}
	return nil
}

func (m *LoraSettings) GetUplinkCounter() uint32 {
	if m != nil {
		return m.UplinkCounter
	}
	return 0
}

func (m *LoraSettings) GetDownlinkCounter() uint32 {
	if m != nil {
		return m.DownlinkCounter
	}
	return 0
}

//*
// I may break this into a MetaRecord.
type DataRecord struct {
	LoggedReading        *LoggedReading        `protobuf:"bytes,1,opt,name=loggedReading,proto3" json:"loggedReading,omitempty"`
	Metadata             *Metadata             `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Log                  *LogMessage           `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	Logs                 []*LogMessage         `protobuf:"bytes,13,rep,name=logs,proto3" json:"logs,omitempty"`
	Status               *Status               `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Readings             *Readings             `protobuf:"bytes,5,opt,name=readings,proto3" json:"readings,omitempty"`
	Modules              []*ModuleInfo         `protobuf:"bytes,6,rep,name=modules,proto3" json:"modules,omitempty"`
	Schedule             *Schedule             `protobuf:"bytes,7,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Meta                 uint64                `protobuf:"varint,8,opt,name=meta,proto3" json:"meta,omitempty"`
	Identity             *Identity             `protobuf:"bytes,9,opt,name=identity,proto3" json:"identity,omitempty"`
	Condition            *Condition            `protobuf:"bytes,10,opt,name=condition,proto3" json:"condition,omitempty"`
	Lora                 *LoraSettings         `protobuf:"bytes,11,opt,name=lora,proto3" json:"lora,omitempty"`
	Network              *NetworkSettings      `protobuf:"bytes,12,opt,name=network,proto3" json:"network,omitempty"`
	Transmission         *TransmissionSettings `protobuf:"bytes,14,opt,name=transmission,proto3" json:"transmission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DataRecord) Reset()         { *m = DataRecord{} }
func (m *DataRecord) String() string { return proto.CompactTextString(m) }
func (*DataRecord) ProtoMessage()    {}
func (*DataRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{22}
}

func (m *DataRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRecord.Unmarshal(m, b)
}
func (m *DataRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRecord.Marshal(b, m, deterministic)
}
func (m *DataRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRecord.Merge(m, src)
}
func (m *DataRecord) XXX_Size() int {
	return xxx_messageInfo_DataRecord.Size(m)
}
func (m *DataRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DataRecord proto.InternalMessageInfo

func (m *DataRecord) GetLoggedReading() *LoggedReading {
	if m != nil {
		return m.LoggedReading
	}
	return nil
}

func (m *DataRecord) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *DataRecord) GetLog() *LogMessage {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *DataRecord) GetLogs() []*LogMessage {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *DataRecord) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DataRecord) GetReadings() *Readings {
	if m != nil {
		return m.Readings
	}
	return nil
}

func (m *DataRecord) GetModules() []*ModuleInfo {
	if m != nil {
		return m.Modules
	}
	return nil
}

func (m *DataRecord) GetSchedule() *Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

func (m *DataRecord) GetMeta() uint64 {
	if m != nil {
		return m.Meta
	}
	return 0
}

func (m *DataRecord) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *DataRecord) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *DataRecord) GetLora() *LoraSettings {
	if m != nil {
		return m.Lora
	}
	return nil
}

func (m *DataRecord) GetNetwork() *NetworkSettings {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *DataRecord) GetTransmission() *TransmissionSettings {
	if m != nil {
		return m.Transmission
	}
	return nil
}

type SignedRecord struct {
	Kind                 SignedRecordKind `protobuf:"varint,1,opt,name=kind,proto3,enum=fk_data.SignedRecordKind" json:"kind,omitempty"`
	Time                 int64            `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Data                 []byte           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Hash                 []byte           `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Record               uint64           `protobuf:"varint,5,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SignedRecord) Reset()         { *m = SignedRecord{} }
func (m *SignedRecord) String() string { return proto.CompactTextString(m) }
func (*SignedRecord) ProtoMessage()    {}
func (*SignedRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{23}
}

func (m *SignedRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedRecord.Unmarshal(m, b)
}
func (m *SignedRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedRecord.Marshal(b, m, deterministic)
}
func (m *SignedRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedRecord.Merge(m, src)
}
func (m *SignedRecord) XXX_Size() int {
	return xxx_messageInfo_SignedRecord.Size(m)
}
func (m *SignedRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedRecord.DiscardUnknown(m)
}

var xxx_messageInfo_SignedRecord proto.InternalMessageInfo

func (m *SignedRecord) GetKind() SignedRecordKind {
	if m != nil {
		return m.Kind
	}
	return SignedRecordKind_SIGNED_RECORD_KIND_NONE
}

func (m *SignedRecord) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SignedRecord) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignedRecord) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SignedRecord) GetRecord() uint64 {
	if m != nil {
		return m.Record
	}
	return 0
}

type LoraRecord struct {
	DeviceId             []byte    `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Time                 int64     `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Number               uint64    `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Module               uint32    `protobuf:"varint,4,opt,name=module,proto3" json:"module,omitempty"`
	Sensor               uint64    `protobuf:"varint,5,opt,name=sensor,proto3" json:"sensor,omitempty"`
	Values               []float32 `protobuf:"fixed32,6,rep,packed,name=values,proto3" json:"values,omitempty"`
	Data                 []byte    `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoraRecord) Reset()         { *m = LoraRecord{} }
func (m *LoraRecord) String() string { return proto.CompactTextString(m) }
func (*LoraRecord) ProtoMessage()    {}
func (*LoraRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_412c2faa5b3d2004, []int{24}
}

func (m *LoraRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoraRecord.Unmarshal(m, b)
}
func (m *LoraRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoraRecord.Marshal(b, m, deterministic)
}
func (m *LoraRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoraRecord.Merge(m, src)
}
func (m *LoraRecord) XXX_Size() int {
	return xxx_messageInfo_LoraRecord.Size(m)
}
func (m *LoraRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_LoraRecord.DiscardUnknown(m)
}

var xxx_messageInfo_LoraRecord proto.InternalMessageInfo

func (m *LoraRecord) GetDeviceId() []byte {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func (m *LoraRecord) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LoraRecord) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *LoraRecord) GetModule() uint32 {
	if m != nil {
		return m.Module
	}
	return 0
}

func (m *LoraRecord) GetSensor() uint64 {
	if m != nil {
		return m.Sensor
	}
	return 0
}

func (m *LoraRecord) GetValues() []float32 {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *LoraRecord) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("fk_data.DownloadFlags", DownloadFlags_name, DownloadFlags_value)
	proto.RegisterEnum("fk_data.ConditionFlags", ConditionFlags_name, ConditionFlags_value)
	proto.RegisterEnum("fk_data.SignedRecordKind", SignedRecordKind_name, SignedRecordKind_value)
	proto.RegisterType((*DeviceLocation)(nil), "fk_data.DeviceLocation")
	proto.RegisterType((*SensorReading)(nil), "fk_data.SensorReading")
	proto.RegisterType((*LoggedReading)(nil), "fk_data.LoggedReading")
	proto.RegisterType((*SensorAndValue)(nil), "fk_data.SensorAndValue")
	proto.RegisterType((*ModuleHeader)(nil), "fk_data.ModuleHeader")
	proto.RegisterType((*ModuleInfo)(nil), "fk_data.ModuleInfo")
	proto.RegisterType((*SensorInfo)(nil), "fk_data.SensorInfo")
	proto.RegisterType((*Firmware)(nil), "fk_data.Firmware")
	proto.RegisterType((*Metadata)(nil), "fk_data.Metadata")
	proto.RegisterType((*Status)(nil), "fk_data.Status")
	proto.RegisterType((*LogMessage)(nil), "fk_data.LogMessage")
	proto.RegisterType((*SensorGroup)(nil), "fk_data.SensorGroup")
	proto.RegisterType((*Readings)(nil), "fk_data.Readings")
	proto.RegisterType((*JobSchedule)(nil), "fk_data.JobSchedule")
	proto.RegisterType((*Schedule)(nil), "fk_data.Schedule")
	proto.RegisterType((*Identity)(nil), "fk_data.Identity")
	proto.RegisterType((*Condition)(nil), "fk_data.Condition")
	proto.RegisterType((*NetworkInfo)(nil), "fk_data.NetworkInfo")
	proto.RegisterType((*WifiTransmission)(nil), "fk_data.WifiTransmission")
	proto.RegisterType((*TransmissionSettings)(nil), "fk_data.TransmissionSettings")
	proto.RegisterType((*NetworkSettings)(nil), "fk_data.NetworkSettings")
	proto.RegisterType((*LoraSettings)(nil), "fk_data.LoraSettings")
	proto.RegisterType((*DataRecord)(nil), "fk_data.DataRecord")
	proto.RegisterType((*SignedRecord)(nil), "fk_data.SignedRecord")
	proto.RegisterType((*LoraRecord)(nil), "fk_data.LoraRecord")
}

func init() {
	proto.RegisterFile("fk-data.proto", fileDescriptor_412c2faa5b3d2004)
}

var fileDescriptor_412c2faa5b3d2004 = []byte{
	// 1764 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x18, 0xcd, 0x6e, 0x23, 0x49,
	0x99, 0xb6, 0x9d, 0xd8, 0xfe, 0x6c, 0x67, 0xbc, 0xb5, 0x21, 0xeb, 0xdd, 0xcd, 0x84, 0xa8, 0xb5,
	0xb0, 0x61, 0x44, 0xa2, 0x51, 0xf6, 0xc2, 0x01, 0x81, 0xbc, 0x89, 0x67, 0xc6, 0x4c, 0xe2, 0x48,
	0xe5, 0x2c, 0x2b, 0x71, 0x09, 0x65, 0x77, 0xd9, 0x53, 0xa4, 0xdd, 0x6d, 0xaa, 0xbb, 0x13, 0xc2,
	0x99, 0x0b, 0x07, 0x24, 0xb8, 0xf0, 0x1a, 0xf0, 0x04, 0x3c, 0x01, 0x12, 0xcf, 0xc1, 0x3b, 0x20,
	0x81, 0xea, 0xab, 0x9f, 0xae, 0xf6, 0x5a, 0xda, 0x9d, 0x5b, 0x7d, 0x3f, 0x55, 0xdf, 0xff, 0x4f,
	0x37, 0xf4, 0x16, 0xf7, 0xa7, 0x11, 0xcb, 0xd9, 0xd9, 0x5a, 0xa6, 0x79, 0x4a, 0x9a, 0x8b, 0xfb,
	0x3b, 0x05, 0x86, 0xff, 0x0d, 0x60, 0xef, 0x92, 0x3f, 0x88, 0x39, 0xbf, 0x4a, 0xe7, 0x2c, 0x17,
	0x69, 0x42, 0x06, 0xd0, 0xe4, 0x09, 0x9b, 0xc5, 0x3c, 0x1a, 0x34, 0x8f, 0x83, 0x93, 0x1e, 0xb5,
	0x20, 0xe9, 0x43, 0x7d, 0x21, 0x7e, 0x3f, 0x08, 0x10, 0xab, 0x8e, 0x84, 0x40, 0x23, 0x17, 0x2b,
	0x3e, 0xa8, 0x1d, 0x07, 0x27, 0x75, 0x8a, 0x67, 0x72, 0x08, 0xed, 0x38, 0x4d, 0x96, 0x22, 0x2f,
	0x22, 0x3e, 0xa8, 0x1f, 0x07, 0x27, 0x35, 0x5a, 0x22, 0xc8, 0x27, 0xd0, 0x8a, 0x59, 0xae, 0x89,
	0x0d, 0x24, 0x3a, 0x58, 0xd1, 0x58, 0x6c, 0x68, 0x3b, 0x9a, 0x66, 0x61, 0x72, 0x0c, 0x9d, 0x79,
	0x9a, 0xca, 0x48, 0x24, 0x2c, 0xe7, 0xd9, 0x60, 0xf7, 0xb8, 0x7e, 0x52, 0xa3, 0x3e, 0x8a, 0x1c,
	0x01, 0x64, 0x2c, 0xe7, 0x71, 0x2c, 0x14, 0x43, 0x0b, 0x95, 0xf4, 0x30, 0x4a, 0xd7, 0x77, 0x51,
	0xba, 0x1e, 0xb4, 0x91, 0x82, 0xe7, 0xf0, 0x1e, 0x7a, 0x53, 0x9e, 0x64, 0xa9, 0xa4, 0x9c, 0x45,
	0x22, 0x59, 0x2a, 0xe3, 0xa5, 0x3e, 0x1a, 0x33, 0x2d, 0xb8, 0xd5, 0xd4, 0x03, 0xd8, 0xcd, 0xf0,
	0x3a, 0xda, 0xd9, 0xa3, 0x06, 0x22, 0xfb, 0xb0, 0xf3, 0xc0, 0xe2, 0xc2, 0x5a, 0xa8, 0x81, 0xf0,
	0x2f, 0x01, 0xf4, 0xae, 0xd2, 0xe5, 0x92, 0x47, 0x9e, 0xb4, 0x07, 0x2e, 0x33, 0x91, 0x26, 0x56,
	0x9a, 0x01, 0xc9, 0x17, 0xd0, 0x8a, 0x4d, 0x40, 0x50, 0x62, 0xe7, 0xfc, 0xa3, 0x33, 0x13, 0xb3,
	0xb3, 0x6a, 0xbc, 0xa8, 0x63, 0x24, 0x2f, 0x4b, 0xe5, 0xeb, 0x78, 0xe7, 0xc0, 0xdd, 0xa9, 0x58,
	0xe9, 0x8c, 0x0a, 0x7f, 0x0e, 0x7b, 0x9a, 0x32, 0x4c, 0xa2, 0x5f, 0x29, 0x25, 0x3d, 0x93, 0x82,
	0xed, 0x26, 0xd5, 0x7c, 0x93, 0x7e, 0x03, 0xdd, 0xeb, 0x34, 0x2a, 0x62, 0xfe, 0x86, 0xb3, 0x88,
	0x4b, 0x12, 0x42, 0x77, 0xc5, 0x92, 0x62, 0xc1, 0xe6, 0x79, 0x21, 0xb9, 0x7d, 0xa3, 0x82, 0x53,
	0x8e, 0xbc, 0x17, 0x49, 0x84, 0x0f, 0xf5, 0x28, 0x9e, 0x7d, 0x47, 0xd4, 0x2b, 0x8e, 0x08, 0xff,
	0x54, 0x03, 0xd0, 0x22, 0xc6, 0xc9, 0x22, 0x55, 0x29, 0xb2, 0x4e, 0x33, 0x91, 0x97, 0x2e, 0x73,
	0xb0, 0x7a, 0x84, 0x45, 0x91, 0xe4, 0x59, 0x66, 0xde, 0xb6, 0xa0, 0x12, 0x99, 0xb0, 0x95, 0xce,
	0xc6, 0x36, 0xc5, 0x33, 0x39, 0x85, 0xdd, 0x77, 0xa8, 0x34, 0x06, 0xa9, 0x73, 0xfe, 0x7d, 0xe7,
	0x2b, 0xdf, 0x22, 0x6a, 0x98, 0xc8, 0x29, 0xb4, 0x16, 0x42, 0xae, 0x1e, 0x99, 0xd4, 0xb9, 0xd9,
	0x39, 0xff, 0xc0, 0x5d, 0x78, 0x65, 0x08, 0xd4, 0xb1, 0x90, 0x53, 0x68, 0x6a, 0xc7, 0xe9, 0x54,
	0xed, 0x9c, 0x7f, 0xb8, 0x11, 0x0a, 0x65, 0x0d, 0xb5, 0x3c, 0x64, 0x0f, 0x6a, 0x42, 0x97, 0x5b,
	0x97, 0xd6, 0x44, 0xa4, 0xbc, 0xbd, 0x88, 0xd9, 0xd2, 0xa6, 0xb1, 0x06, 0xc2, 0x1c, 0xa0, 0xbc,
	0xac, 0x22, 0x95, 0x14, 0xab, 0x99, 0xf3, 0xb2, 0x81, 0x9c, 0xb1, 0x35, 0xcf, 0xd8, 0xcf, 0xa0,
	0x57, 0x24, 0x22, 0xbf, 0x59, 0x5c, 0x73, 0x96, 0x15, 0xd2, 0x7a, 0xa2, 0x8a, 0x2c, 0xa5, 0x36,
	0x7c, 0xa9, 0x7f, 0x0c, 0xa0, 0x65, 0x2d, 0xdc, 0xcc, 0xd8, 0x76, 0x99, 0xb1, 0xfb, 0xb0, 0x33,
	0x2b, 0x44, 0x1c, 0x19, 0xb9, 0x1a, 0xf0, 0x94, 0xd4, 0x12, 0xad, 0x92, 0x87, 0xd0, 0x56, 0x15,
	0x94, 0xe5, 0x6c, 0xb5, 0x46, 0x71, 0x0d, 0x5a, 0x22, 0xb0, 0x54, 0x59, 0xf6, 0x0e, 0x1d, 0xdd,
	0xa6, 0x78, 0x0e, 0xff, 0x5e, 0x83, 0xd6, 0x35, 0xcf, 0x99, 0xf2, 0xa1, 0x4a, 0x83, 0x08, 0xab,
	0x60, 0x1c, 0xa1, 0x1e, 0x5d, 0xea, 0xe0, 0xad, 0x85, 0xda, 0x87, 0xfa, 0x52, 0xe4, 0x46, 0x07,
	0x75, 0x2c, 0xd5, 0x6d, 0xfa, 0xea, 0x1e, 0x01, 0x48, 0x9e, 0xf1, 0xfc, 0x82, 0x15, 0x19, 0x37,
	0x6e, 0xf0, 0x30, 0x7e, 0x58, 0x77, 0xbe, 0x43, 0x58, 0x4f, 0xa1, 0xb9, 0xc2, 0x64, 0xfa, 0x66,
	0x16, 0x94, 0x39, 0x4d, 0x2d, 0x4f, 0x25, 0xc7, 0x5a, 0xdf, 0x9e, 0x63, 0x47, 0x00, 0x4b, 0x9e,
	0x70, 0xa9, 0xbb, 0x44, 0x1b, 0xdd, 0xe0, 0x61, 0xc2, 0x3f, 0xc0, 0xee, 0x34, 0x67, 0x79, 0x91,
	0x39, 0x97, 0x04, 0xd5, 0xde, 0x55, 0xac, 0x9d, 0xa3, 0x7a, 0xd4, 0x40, 0x2a, 0xc2, 0x33, 0x96,
	0xe7, 0x5c, 0x3e, 0x99, 0xe6, 0x6d, 0x41, 0x75, 0x63, 0xc5, 0x57, 0xa9, 0x7c, 0x32, 0x8e, 0x31,
	0x90, 0x7a, 0x7d, 0x56, 0x64, 0x4f, 0x18, 0xad, 0x06, 0xc5, 0xb3, 0x4a, 0x1a, 0xb8, 0x4a, 0x97,
	0xd7, 0x3c, 0xcb, 0xd8, 0x92, 0xbf, 0x97, 0x02, 0xfb, 0xb0, 0x13, 0xf3, 0x07, 0x1e, 0x9b, 0x4e,
	0xa0, 0x01, 0x15, 0xf1, 0x05, 0x9b, 0x8b, 0x58, 0xe4, 0x5a, 0x7c, 0x9b, 0x3a, 0x58, 0xa9, 0xbc,
	0xd2, 0x82, 0x4c, 0xc6, 0x58, 0x30, 0xfc, 0x35, 0x74, 0x74, 0x5c, 0x5e, 0xcb, 0xb4, 0x58, 0xa3,
	0x05, 0xe8, 0x6b, 0x5b, 0x32, 0x1a, 0x52, 0xdd, 0xd6, 0x74, 0x44, 0xd5, 0x3a, 0xea, 0x95, 0x6e,
	0x5b, 0xed, 0x8f, 0xd4, 0x31, 0x86, 0xff, 0x09, 0xa0, 0x65, 0x1a, 0xea, 0x76, 0x0f, 0x7b, 0xb3,
	0xa4, 0x56, 0x9d, 0x25, 0xae, 0xd0, 0xea, 0x5e, 0xa1, 0xa9, 0x37, 0x56, 0x3c, 0x67, 0x83, 0x5d,
	0xdd, 0x18, 0xd5, 0xd9, 0x73, 0x52, 0xb3, 0xe2, 0x24, 0x7f, 0x3e, 0x34, 0xbe, 0xeb, 0x7c, 0xf8,
	0x29, 0x74, 0xb3, 0xd2, 0x1b, 0x36, 0x85, 0xf7, 0x37, 0x4c, 0x45, 0x22, 0xad, 0x70, 0x86, 0x7f,
	0x0e, 0xa0, 0xf3, 0xcb, 0x74, 0x36, 0x9d, 0xbf, 0xe3, 0xe8, 0x30, 0x02, 0x8d, 0xb9, 0x34, 0x3d,
	0xa0, 0x4b, 0xf1, 0xac, 0x22, 0x24, 0x92, 0x9c, 0xcb, 0x07, 0x16, 0x1b, 0x7b, 0x1d, 0xac, 0x68,
	0x92, 0xaf, 0x39, 0xcb, 0x79, 0x64, 0x6c, 0x76, 0x30, 0xd6, 0x72, 0x21, 0x4b, 0x53, 0x7a, 0xd4,
	0xc1, 0xca, 0xfc, 0xdf, 0x0a, 0x95, 0x7d, 0x18, 0xd8, 0x1e, 0x35, 0x50, 0xf8, 0xcf, 0x00, 0x5a,
	0x4e, 0x99, 0x97, 0x5e, 0xf4, 0x02, 0xf4, 0x45, 0x69, 0x92, 0xa7, 0x74, 0x19, 0x3a, 0x72, 0x06,
	0xcd, 0x84, 0xe7, 0x8f, 0xa9, 0xbc, 0x37, 0xc3, 0x75, 0xfb, 0x05, 0xcb, 0x44, 0x4e, 0xa0, 0x11,
	0xa7, 0x92, 0x99, 0xa9, 0xba, 0x9d, 0x19, 0x39, 0xc8, 0x8f, 0xa0, 0xbe, 0x5c, 0x67, 0x26, 0x24,
	0xdb, 0x19, 0x15, 0x43, 0x78, 0x04, 0xad, 0x71, 0xc4, 0x93, 0x5c, 0xa5, 0xaf, 0x6d, 0xd8, 0x41,
	0xd9, 0xb0, 0xc3, 0x5f, 0x40, 0xfb, 0x22, 0x4d, 0x22, 0x3d, 0xd8, 0x5c, 0xba, 0x04, 0x7e, 0xba,
	0x1c, 0x42, 0x5b, 0xf2, 0x39, 0xee, 0x3f, 0x36, 0xc1, 0x4a, 0x44, 0x98, 0x41, 0x67, 0xa2, 0xb5,
	0xc7, 0x61, 0x41, 0xa0, 0x91, 0x65, 0x22, 0xb2, 0x32, 0xd4, 0x19, 0x67, 0x29, 0xcb, 0xb2, 0xc7,
	0x54, 0xda, 0xa6, 0xed, 0x60, 0xe5, 0xf8, 0xb9, 0x54, 0xf1, 0x41, 0x9b, 0x5b, 0xd4, 0x40, 0x4a,
	0xe8, 0x5a, 0xf2, 0x05, 0x97, 0x92, 0x47, 0x68, 0x65, 0x8b, 0x96, 0x88, 0xf0, 0x16, 0xfa, 0x5f,
	0x8b, 0x85, 0xb8, 0x95, 0x2c, 0xc9, 0x56, 0x22, 0xc3, 0xb9, 0xd0, 0x87, 0x7a, 0x21, 0x63, 0x23,
	0x58, 0x1d, 0x95, 0x39, 0x79, 0x7a, 0xcf, 0x13, 0x3b, 0x29, 0x10, 0xf0, 0xd7, 0x4e, 0x2d, 0xd2,
	0x82, 0xe1, 0x08, 0xf6, 0xfd, 0x17, 0xa7, 0x3c, 0xcf, 0x31, 0x8a, 0xa7, 0xd0, 0x78, 0x14, 0x0b,
	0x61, 0x62, 0xfe, 0xb1, 0x73, 0xf6, 0xa6, 0x0a, 0x14, 0xd9, 0xc2, 0x0b, 0x78, 0x66, 0x3c, 0xe2,
	0x5e, 0x78, 0x09, 0x2d, 0x13, 0x62, 0xe5, 0xdb, 0x6a, 0x31, 0x78, 0xde, 0xa3, 0x8e, 0x2b, 0xfc,
	0x57, 0x0d, 0xba, 0x57, 0xa9, 0x64, 0xee, 0x89, 0x43, 0x68, 0xeb, 0xc9, 0x33, 0x2a, 0x84, 0x29,
	0x87, 0x12, 0xa1, 0xdc, 0xc8, 0xd6, 0xeb, 0xb7, 0xfc, 0x09, 0x6d, 0xed, 0x52, 0x03, 0x19, 0xbc,
	0xba, 0x52, 0x77, 0x78, 0xc5, 0xff, 0x19, 0xf4, 0x16, 0x92, 0xff, 0xae, 0xe0, 0xc9, 0xfc, 0xe9,
	0x4b, 0x96, 0x44, 0xa6, 0x20, 0xaa, 0x48, 0xc5, 0xa5, 0x45, 0x0c, 0xcd, 0xba, 0xb3, 0x83, 0x8f,
	0x54, 0x91, 0xe4, 0x27, 0xf0, 0x41, 0x62, 0xed, 0x45, 0x3f, 0x28, 0x35, 0x76, 0x91, 0xf3, 0x9b,
	0x04, 0xf5, 0x26, 0x5b, 0xaf, 0x3d, 0x4e, 0xbd, 0x8c, 0x54, 0x91, 0xb8, 0x47, 0xac, 0x63, 0x91,
	0xdc, 0x5f, 0xa4, 0x85, 0xaa, 0x6d, 0xb3, 0x9f, 0x54, 0x91, 0xe4, 0x04, 0x9e, 0x45, 0xe9, 0x63,
	0xe2, 0xf3, 0xe9, 0xa5, 0x7b, 0x13, 0x1d, 0xfe, 0x6d, 0x07, 0xe0, 0x92, 0xe5, 0x8c, 0x62, 0xde,
	0x92, 0x9f, 0x41, 0x2f, 0xf6, 0x17, 0x64, 0x13, 0xda, 0x72, 0x8d, 0xad, 0xac, 0xcf, 0xb4, 0xca,
	0xac, 0xc6, 0xe7, 0xca, 0x2c, 0x08, 0xa6, 0xac, 0xcb, 0xf1, 0x69, 0x37, 0x07, 0xea, 0x58, 0xc8,
	0x0f, 0xa1, 0x1e, 0xa7, 0x76, 0x53, 0xfe, 0xd0, 0x17, 0x61, 0xa6, 0x16, 0x55, 0x74, 0xf2, 0xb9,
	0xaa, 0xfd, 0x65, 0x36, 0xe8, 0x6d, 0x0c, 0x70, 0x8f, 0x0f, 0x19, 0xc8, 0xe7, 0xb0, 0x9b, 0xe1,
	0xb8, 0x35, 0xd5, 0xff, 0xac, 0xec, 0xab, 0x88, 0xa6, 0x86, 0xac, 0xf4, 0x74, 0xfd, 0x6a, 0x73,
	0x95, 0xb4, 0x03, 0xc5, 0x6b, 0x56, 0xef, 0xbf, 0x44, 0x64, 0xa6, 0xd5, 0x60, 0x0c, 0xfd, 0xd7,
	0xcb, 0x56, 0x98, 0x79, 0x9d, 0x1c, 0x87, 0x4e, 0x4b, 0x0f, 0x6f, 0x1c, 0x3a, 0xa7, 0xd0, 0x12,
	0xa6, 0x39, 0x61, 0xe0, 0xfc, 0x27, 0x6c, 0xd7, 0xa2, 0x8e, 0x85, 0xbc, 0x84, 0xf6, 0xdc, 0xf6,
	0xaa, 0x01, 0x20, 0x3f, 0x71, 0xfc, 0xae, 0x8b, 0xd1, 0x92, 0x89, 0xfc, 0xd8, 0xf4, 0xd3, 0xce,
	0xc6, 0xe6, 0xed, 0x57, 0x96, 0x69, 0xa8, 0xe7, 0x65, 0xab, 0xee, 0x22, 0xf7, 0x60, 0xb3, 0x42,
	0xdd, 0x05, 0xd7, 0xae, 0x87, 0xd0, 0xcd, 0xbd, 0xfa, 0x1f, 0xec, 0xe1, 0xc5, 0xe7, 0xee, 0xe2,
	0xb6, 0x6e, 0x42, 0x2b, 0x57, 0xc2, 0xbf, 0x06, 0xd0, 0x9d, 0x8a, 0x65, 0xa2, 0xb2, 0x0b, 0x53,
	0xf3, 0xd4, 0x7c, 0xb5, 0xa8, 0x8c, 0xdc, 0xf3, 0x9a, 0x8d, 0xcf, 0xf4, 0x56, 0x24, 0x91, 0xf9,
	0xa0, 0xd9, 0xb6, 0x84, 0x12, 0x68, 0x60, 0x6e, 0xea, 0x92, 0xc7, 0xb3, 0xdb, 0x74, 0x1b, 0x1a,
	0xa7, 0xce, 0xaa, 0x39, 0xe8, 0x3e, 0x6e, 0x36, 0x2a, 0x03, 0x85, 0xff, 0xc0, 0x9d, 0x4a, 0xda,
	0x62, 0x79, 0xdf, 0x1d, 0xb8, 0xba, 0x8a, 0x37, 0xdc, 0x2a, 0x5e, 0x2e, 0x45, 0x8d, 0xca, 0x52,
	0x54, 0x7e, 0x09, 0x1a, 0x35, 0xcc, 0x97, 0xe0, 0x01, 0xec, 0xe2, 0xc7, 0x9f, 0xfd, 0x08, 0x37,
	0x90, 0x33, 0xaf, 0x59, 0x9a, 0xf7, 0x62, 0x06, 0xbd, 0x4b, 0x55, 0xf2, 0x29, 0x8b, 0x5e, 0xe1,
	0xd0, 0x3a, 0x00, 0x42, 0x47, 0xc3, 0xcb, 0xf1, 0xe4, 0xf5, 0xdd, 0xab, 0xab, 0xe1, 0xeb, 0xe9,
	0xdd, 0xe4, 0x66, 0x32, 0xea, 0x7f, 0x8f, 0xfc, 0x00, 0x3e, 0xdd, 0xc4, 0xdf, 0xde, 0xd1, 0xd1,
	0xc5, 0x0d, 0x55, 0xb8, 0x7e, 0x40, 0x06, 0xb0, 0x5f, 0x65, 0xb8, 0x1e, 0x4e, 0xbe, 0x1a, 0x5e,
	0xf5, 0x6b, 0x2f, 0xc6, 0xb0, 0xe7, 0x92, 0x4c, 0x0b, 0x19, 0xc0, 0xfe, 0xc5, 0xcd, 0xe4, 0x72,
	0x7c, 0x3b, 0xbe, 0x99, 0x54, 0xc5, 0x3c, 0x87, 0x8f, 0x37, 0x29, 0x9e, 0x90, 0x17, 0xff, 0x0e,
	0xa0, 0xbf, 0x19, 0x50, 0xf2, 0x29, 0x7c, 0x34, 0x1d, 0xbf, 0x9e, 0x8c, 0x2e, 0x0d, 0xeb, 0xdd,
	0xdb, 0xf1, 0xe4, 0xd2, 0x3e, 0x78, 0x04, 0x9f, 0x6c, 0x21, 0x5e, 0xdf, 0x5c, 0x7e, 0x75, 0x35,
	0x9a, 0xf6, 0x03, 0x65, 0xd7, 0x16, 0xfa, 0xf4, 0xe2, 0xcd, 0x48, 0x71, 0xf4, 0x6b, 0xe4, 0x10,
	0x06, 0xdb, 0x18, 0x6e, 0x87, 0xb7, 0xa3, 0x7e, 0x9d, 0x1c, 0xc3, 0xe1, 0x16, 0x2a, 0x1d, 0x7e,
	0x6d, 0x38, 0x1a, 0xe4, 0xf9, 0xd6, 0xfb, 0x37, 0xb7, 0x6f, 0x46, 0xb4, 0xff, 0xbf, 0xe0, 0xcb,
	0x03, 0xd8, 0x4f, 0xe5, 0xf2, 0x6c, 0x21, 0x78, 0x1c, 0xdd, 0x8b, 0xfc, 0x4c, 0xff, 0x03, 0x9a,
	0xcd, 0x76, 0xf1, 0x3f, 0xd0, 0x17, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x4e, 0x9f, 0x2d,
	0x18, 0x12, 0x00, 0x00,
}
