/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "fk-data.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fk_data_DeviceLocation, fk_data_DeviceLocation, AUTO)


PB_BIND(fk_data_SensorReading, fk_data_SensorReading, AUTO)


PB_BIND(fk_data_LoggedReading, fk_data_LoggedReading, AUTO)


PB_BIND(fk_data_SensorAndValue, fk_data_SensorAndValue, AUTO)


PB_BIND(fk_data_ModuleInfo, fk_data_ModuleInfo, AUTO)


PB_BIND(fk_data_SensorInfo, fk_data_SensorInfo, AUTO)


PB_BIND(fk_data_Firmware, fk_data_Firmware, AUTO)


PB_BIND(fk_data_Metadata, fk_data_Metadata, AUTO)


PB_BIND(fk_data_Status, fk_data_Status, AUTO)


PB_BIND(fk_data_LogMessage, fk_data_LogMessage, AUTO)


PB_BIND(fk_data_ReadingsGroup, fk_data_ReadingsGroup, AUTO)


PB_BIND(fk_data_DataRecord, fk_data_DataRecord, 2)




/* @@protoc_insertion_point(eof) */
